kube:
  - network-type: flannel
  - load-balancers:
    - type: nginx
    - servers:
      - server: 1.2.3.4
      - server: 1.2.3.5 
  - workers:
    - server: 2.3.4.5
    - server: 3.3.4.5
  - masters:
    - server: 2.3.4.6
    - server: 3.3.4.6
  