kube:
  - version: 1.28
  - network-type: flannel
  - masters:
    - server: 192.168.0.60
    - server: 192.168.0.63
    - server: 192.168.0.64
  - workers:
    - server: 192.168.0.65
    - server: 192.168.0.66
    - server: 192.168.0.67